services:
  backend-demo:
    image: backend-demo:latest
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - MONGO_CONNECTION_STRING=mongodb://admin:changeme@mongo:27017/test-db-leya?authSource=admin
      - SECRET_KEY=12345678qwertyuio
    networks:
      - backend-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
    networks:
      - backend-network

networks:
  backend-network: